name: cam_mic_testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  audioplayers: ^6.2.0
  camera: ^0.11.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_sound: ^9.23.1
  flutter_webrtc: ^0.12.11
  google_mlkit_face_detection: ^0.12.0
  just_audio: ^0.9.46
  mic_stream: ^0.7.1+2
  microphone: ^0.1.0
  permission_handler: ^11.4.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
